%Generated by org.bbop.experiments.SimpleFactBaseGenerator

term('ID:1','Label for 1','Textual defintion for 1').
term('ID:2','Label for 2','Textual defintion for 2').
isTriple('ID:2', subClassOf,'ID:1').
term('ID:3','Label for 3','Textual defintion for 3').
isTriple('ID:3', subClassOf,'ID:1').
term('ID:4','Label for 4','Textual defintion for 4').
isTriple('ID:4', subClassOf,'ID:2').
term('ID:5','Label for 5','Textual defintion for 5').
isTriple('ID:5', subClassOf,'ID:2').
term('ID:6','Label for 6','Textual defintion for 6').
isTriple('ID:6', subClassOf,'ID:3').
term('ID:7','Label for 7','Textual defintion for 7').
isTriple('ID:7', subClassOf,'ID:3').
term('ID:8','Label for 8','Textual defintion for 8').
isTriple('ID:8', subClassOf,'ID:4').
term('ID:9','Label for 9','Textual defintion for 9').
isTriple('ID:9', subClassOf,'ID:4').
term('ID:10','Label for 10','Textual defintion for 10').
isTriple('ID:10', subClassOf,'ID:5').
term('ID:11','Label for 11','Textual defintion for 11').
isTriple('ID:11', subClassOf,'ID:5').
term('ID:12','Label for 12','Textual defintion for 12').
isTriple('ID:12', subClassOf,'ID:6').
term('ID:13','Label for 13','Textual defintion for 13').
isTriple('ID:13', subClassOf,'ID:6').
term('ID:14','Label for 14','Textual defintion for 14').
isTriple('ID:14', subClassOf,'ID:7').
term('ID:15','Label for 15','Textual defintion for 15').
isTriple('ID:15', subClassOf,'ID:7').
term('ID:16','Label for 16','Textual defintion for 16').
isTriple('ID:16', subClassOf,'ID:8').
term('ID:17','Label for 17','Textual defintion for 17').
isTriple('ID:17', subClassOf,'ID:8').
term('ID:18','Label for 18','Textual defintion for 18').
isTriple('ID:18', subClassOf,'ID:9').
term('ID:19','Label for 19','Textual defintion for 19').
isTriple('ID:19', subClassOf,'ID:9').
term('ID:20','Label for 20','Textual defintion for 20').
isTriple('ID:20', subClassOf,'ID:10').
term('ID:21','Label for 21','Textual defintion for 21').
isTriple('ID:21', subClassOf,'ID:10').
term('ID:22','Label for 22','Textual defintion for 22').
isTriple('ID:22', subClassOf,'ID:11').
term('ID:23','Label for 23','Textual defintion for 23').
isTriple('ID:23', subClassOf,'ID:11').
term('ID:24','Label for 24','Textual defintion for 24').
isTriple('ID:24', subClassOf,'ID:12').
term('ID:25','Label for 25','Textual defintion for 25').
isTriple('ID:25', subClassOf,'ID:12').
term('ID:26','Label for 26','Textual defintion for 26').
isTriple('ID:26', subClassOf,'ID:13').
term('ID:27','Label for 27','Textual defintion for 27').
isTriple('ID:27', subClassOf,'ID:13').
term('ID:28','Label for 28','Textual defintion for 28').
isTriple('ID:28', subClassOf,'ID:14').
term('ID:29','Label for 29','Textual defintion for 29').
isTriple('ID:29', subClassOf,'ID:14').
term('ID:30','Label for 30','Textual defintion for 30').
isTriple('ID:30', subClassOf,'ID:15').
term('ID:31','Label for 31','Textual defintion for 31').
isTriple('ID:31', subClassOf,'ID:15').
term('ID:32','Label for 32','Textual defintion for 32').
isTriple('ID:32', subClassOf,'ID:16').
term('ID:33','Label for 33','Textual defintion for 33').
isTriple('ID:33', subClassOf,'ID:16').
term('ID:34','Label for 34','Textual defintion for 34').
isTriple('ID:34', subClassOf,'ID:17').
term('ID:35','Label for 35','Textual defintion for 35').
isTriple('ID:35', subClassOf,'ID:17').
term('ID:36','Label for 36','Textual defintion for 36').
isTriple('ID:36', subClassOf,'ID:18').
term('ID:37','Label for 37','Textual defintion for 37').
isTriple('ID:37', subClassOf,'ID:18').
term('ID:38','Label for 38','Textual defintion for 38').
isTriple('ID:38', subClassOf,'ID:19').
term('ID:39','Label for 39','Textual defintion for 39').
isTriple('ID:39', subClassOf,'ID:19').
term('ID:40','Label for 40','Textual defintion for 40').
isTriple('ID:40', subClassOf,'ID:20').
term('ID:41','Label for 41','Textual defintion for 41').
isTriple('ID:41', subClassOf,'ID:20').
term('ID:42','Label for 42','Textual defintion for 42').
isTriple('ID:42', subClassOf,'ID:21').
term('ID:43','Label for 43','Textual defintion for 43').
isTriple('ID:43', subClassOf,'ID:21').
term('ID:44','Label for 44','Textual defintion for 44').
isTriple('ID:44', subClassOf,'ID:22').
term('ID:45','Label for 45','Textual defintion for 45').
isTriple('ID:45', subClassOf,'ID:22').
term('ID:46','Label for 46','Textual defintion for 46').
isTriple('ID:46', subClassOf,'ID:23').
term('ID:47','Label for 47','Textual defintion for 47').
isTriple('ID:47', subClassOf,'ID:23').
term('ID:48','Label for 48','Textual defintion for 48').
isTriple('ID:48', subClassOf,'ID:24').
term('ID:49','Label for 49','Textual defintion for 49').
isTriple('ID:49', subClassOf,'ID:24').
term('ID:50','Label for 50','Textual defintion for 50').
isTriple('ID:50', subClassOf,'ID:25').
term('ID:51','Label for 51','Textual defintion for 51').
isTriple('ID:51', subClassOf,'ID:25').
term('ID:52','Label for 52','Textual defintion for 52').
isTriple('ID:52', subClassOf,'ID:26').
term('ID:53','Label for 53','Textual defintion for 53').
isTriple('ID:53', subClassOf,'ID:26').
term('ID:54','Label for 54','Textual defintion for 54').
isTriple('ID:54', subClassOf,'ID:27').
term('ID:55','Label for 55','Textual defintion for 55').
isTriple('ID:55', subClassOf,'ID:27').
term('ID:56','Label for 56','Textual defintion for 56').
isTriple('ID:56', subClassOf,'ID:28').
term('ID:57','Label for 57','Textual defintion for 57').
isTriple('ID:57', subClassOf,'ID:28').
term('ID:58','Label for 58','Textual defintion for 58').
isTriple('ID:58', subClassOf,'ID:29').
term('ID:59','Label for 59','Textual defintion for 59').
isTriple('ID:59', subClassOf,'ID:29').
term('ID:60','Label for 60','Textual defintion for 60').
isTriple('ID:60', subClassOf,'ID:30').
term('ID:61','Label for 61','Textual defintion for 61').
isTriple('ID:61', subClassOf,'ID:30').
term('ID:62','Label for 62','Textual defintion for 62').
isTriple('ID:62', subClassOf,'ID:31').
term('ID:63','Label for 63','Textual defintion for 63').
isTriple('ID:63', subClassOf,'ID:31').
term('ID:64','Label for 64','Textual defintion for 64').
isTriple('ID:64', subClassOf,'ID:32').
term('ID:65','Label for 65','Textual defintion for 65').
isTriple('ID:65', subClassOf,'ID:32').
term('ID:66','Label for 66','Textual defintion for 66').
isTriple('ID:66', subClassOf,'ID:33').
term('ID:67','Label for 67','Textual defintion for 67').
isTriple('ID:67', subClassOf,'ID:33').
term('ID:68','Label for 68','Textual defintion for 68').
isTriple('ID:68', subClassOf,'ID:34').
term('ID:69','Label for 69','Textual defintion for 69').
isTriple('ID:69', subClassOf,'ID:34').
term('ID:70','Label for 70','Textual defintion for 70').
isTriple('ID:70', subClassOf,'ID:35').
term('ID:71','Label for 71','Textual defintion for 71').
isTriple('ID:71', subClassOf,'ID:35').
term('ID:72','Label for 72','Textual defintion for 72').
isTriple('ID:72', subClassOf,'ID:36').
term('ID:73','Label for 73','Textual defintion for 73').
isTriple('ID:73', subClassOf,'ID:36').
term('ID:74','Label for 74','Textual defintion for 74').
isTriple('ID:74', subClassOf,'ID:37').
term('ID:75','Label for 75','Textual defintion for 75').
isTriple('ID:75', subClassOf,'ID:37').
term('ID:76','Label for 76','Textual defintion for 76').
isTriple('ID:76', subClassOf,'ID:38').
term('ID:77','Label for 77','Textual defintion for 77').
isTriple('ID:77', subClassOf,'ID:38').
term('ID:78','Label for 78','Textual defintion for 78').
isTriple('ID:78', subClassOf,'ID:39').
term('ID:79','Label for 79','Textual defintion for 79').
isTriple('ID:79', subClassOf,'ID:39').
term('ID:80','Label for 80','Textual defintion for 80').
isTriple('ID:80', subClassOf,'ID:40').
term('ID:81','Label for 81','Textual defintion for 81').
isTriple('ID:81', subClassOf,'ID:40').
term('ID:82','Label for 82','Textual defintion for 82').
isTriple('ID:82', subClassOf,'ID:41').
term('ID:83','Label for 83','Textual defintion for 83').
isTriple('ID:83', subClassOf,'ID:41').
term('ID:84','Label for 84','Textual defintion for 84').
isTriple('ID:84', subClassOf,'ID:42').
term('ID:85','Label for 85','Textual defintion for 85').
isTriple('ID:85', subClassOf,'ID:42').
term('ID:86','Label for 86','Textual defintion for 86').
isTriple('ID:86', subClassOf,'ID:43').
term('ID:87','Label for 87','Textual defintion for 87').
isTriple('ID:87', subClassOf,'ID:43').
term('ID:88','Label for 88','Textual defintion for 88').
isTriple('ID:88', subClassOf,'ID:44').
term('ID:89','Label for 89','Textual defintion for 89').
isTriple('ID:89', subClassOf,'ID:44').
term('ID:90','Label for 90','Textual defintion for 90').
isTriple('ID:90', subClassOf,'ID:45').
term('ID:91','Label for 91','Textual defintion for 91').
isTriple('ID:91', subClassOf,'ID:45').
term('ID:92','Label for 92','Textual defintion for 92').
isTriple('ID:92', subClassOf,'ID:46').
term('ID:93','Label for 93','Textual defintion for 93').
isTriple('ID:93', subClassOf,'ID:46').
term('ID:94','Label for 94','Textual defintion for 94').
isTriple('ID:94', subClassOf,'ID:47').
term('ID:95','Label for 95','Textual defintion for 95').
isTriple('ID:95', subClassOf,'ID:47').
term('ID:96','Label for 96','Textual defintion for 96').
isTriple('ID:96', subClassOf,'ID:48').
term('ID:97','Label for 97','Textual defintion for 97').
isTriple('ID:97', subClassOf,'ID:48').
term('ID:98','Label for 98','Textual defintion for 98').
isTriple('ID:98', subClassOf,'ID:49').
term('ID:99','Label for 99','Textual defintion for 99').
isTriple('ID:99', subClassOf,'ID:49').
term('ID:100','Label for 100','Textual defintion for 100').
isTriple('ID:100', subClassOf,'ID:50').


isID(ID) :- term(ID,Label,TextDef).
isLabel(Label) :- term(ID,Label,TextDef).
isTextDef(TextDef) :- term(ID,Label,TextDef).

isTransitive(subClassOf).
isTransitive(superClassOf).

isTTriple(A, Relation, B) :- isTriple(A, Relation, B), isTransitive(Relation).
isTTriple(A, Relation, C) :- isTriple(A, Relation, B), isTTriple(B, Relation, C), isTransitive(Relation).

isTriple(Subject, superClassOf, Object) :- isTriple(Object, subClassOf, Subject).

