package org.bbop.termgenie.services;

import static org.bbop.termgenie.tools.ErrorMessages.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.log4j.Logger;
import org.bbop.termgenie.core.Ontology;
import org.bbop.termgenie.core.Ontology.AbstractOntologyTerm.DefaultOntologyTerm;
import org.bbop.termgenie.core.Ontology.IRelation;
import org.bbop.termgenie.core.Ontology.OntologyTerm;
import org.bbop.termgenie.core.Ontology.Relation;
import org.bbop.termgenie.core.TemplateField;
import org.bbop.termgenie.core.TemplateField.Cardinality;
import org.bbop.termgenie.core.TermTemplate;
import org.bbop.termgenie.core.rules.TermGenerationEngine;
import org.bbop.termgenie.core.rules.TermGenerationEngine.TermGenerationInput;
import org.bbop.termgenie.core.rules.TermGenerationEngine.TermGenerationOutput;
import org.bbop.termgenie.core.rules.TermGenerationEngine.TermGenerationParameters;
import org.bbop.termgenie.data.JsonGenerationResponse;
import org.bbop.termgenie.data.JsonOntologyTerm;
import org.bbop.termgenie.data.JsonTermGenerationInput;
import org.bbop.termgenie.data.JsonTermGenerationParameter;
import org.bbop.termgenie.data.JsonTermGenerationParameter.JsonOntologyTermIdentifier;
import org.bbop.termgenie.data.JsonTermTemplate;
import org.bbop.termgenie.data.JsonTermTemplate.JsonCardinality;
import org.bbop.termgenie.data.JsonTermTemplate.JsonTemplateField;
import org.bbop.termgenie.data.JsonValidationHint;
import org.bbop.termgenie.ontology.OntologyTaskManager;
import org.bbop.termgenie.ontology.OntologyTaskManager.OntologyTask;
import org.bbop.termgenie.tools.FieldValidatorTool;
import org.bbop.termgenie.tools.OntologyTools;
import org.semanticweb.owlapi.model.OWLObject;

import owltools.graph.OWLGraphEdge;
import owltools.graph.OWLGraphWrapper;
import owltools.graph.OWLGraphWrapper.ISynonym;
import owltools.graph.OWLQuantifiedProperty;

import com.google.inject.Inject;
import com.google.inject.Singleton;

@Singleton
public class GenerateTermsServiceImpl implements GenerateTermsService {

	private static final Logger logger = Logger.getLogger(GenerateTermsServiceImpl.class);

	private final TemplateCache TEMPLATE_CACHE = TemplateCache.getInstance();
	private final OntologyTools ontologyTools;
	private final TermGenerationEngine termGeneration;
	private final JsonTemplateTools jsonTools;

	/**
	 * @param ontologyTools
	 * @param termGeneration
	 */
	@Inject
	GenerateTermsServiceImpl(OntologyTools ontologyTools,
			TermGenerationEngine termGeneration)
	{
		super();
		this.ontologyTools = ontologyTools;
		this.termGeneration = termGeneration;
		this.jsonTools = new JsonTemplateTools();
	}

	@Override
	public List<JsonTermTemplate> availableTermTemplates(String sessionId, String ontologyName) {
		// sanity check
		if (ontologyName == null) {
			// silently ignore this
			return Collections.emptyList();
		}
		Collection<TermTemplate> templates = getTermTemplates(ontologyName);
		if (templates.isEmpty()) {
			// short cut for empty results.
			return Collections.emptyList();
		}

		// encode the templates for JSON
		List<JsonTermTemplate> jsonTemplates = new ArrayList<JsonTermTemplate>();
		for (TermTemplate template : templates) {
			jsonTemplates.add(jsonTools.createJsonTermTemplate(template));
		}
		Collections.sort(jsonTemplates, JsonTermTempleSorter.instance);
		return jsonTemplates;
//		return jsonTemplates.toArray(new JsonTermTemplate[jsonTemplates.size()]);
	}

	/*
	 * Do not trust any input here. Do not assume that this is well formed, as
	 * the request could be generated by a different client!
	 */
	@Override
	public JsonGenerationResponse generateTerms(String sessionId,
			String ontologyName,
			List<JsonTermGenerationInput> allParameters)
	{
		// sanity checks
		if (ontologyName == null || ontologyName.isEmpty()) {
			return new JsonGenerationResponse(NO_ONTOLOGY, null, null);
		}
		if (allParameters == null) {
			return new JsonGenerationResponse(NO_TERM_GENERATION_PARAMETERS, null, null);
		}

		// retrieve target ontology
		OntologyTaskManager manager = ontologyTools.getManager(ontologyName);
		if (manager == null) {
			return new JsonGenerationResponse(NO_ONTOLOGY, null, null);
		}

		// term generation parameter validation
		List<JsonValidationHint> allErrors = new ArrayList<JsonValidationHint>();
		for (JsonTermGenerationInput input : allParameters) {
			if (input == null) {
				return new JsonGenerationResponse(UNEXPECTED_NULL_VALUE, null, null);
			}
			JsonTermTemplate one = input.getTermTemplate();
			JsonTermGenerationParameter parameter = input.getTermGenerationParameter();
			if (one == null || parameter == null) {
				return new JsonGenerationResponse(UNEXPECTED_NULL_VALUE, null, null);
			}
			// retrieve the template from the server, do not trust the submitted
			// one.
			TermTemplate template = getTermTemplate(ontologyName, one.getName());
			if (template == null) {
				return new JsonGenerationResponse("Unknow template specified: " + one.getName(), null, null);
			}
			JsonTermTemplate jsonTermTemplate = jsonTools.createJsonTermTemplate(template);

			List<JsonValidationHint> errors = FieldValidatorTool.validateParameters(template,
					jsonTermTemplate,
					parameter);
			if (!errors.isEmpty()) {
				allErrors.addAll(errors);
			}
		}
		// return validation errors
		if (!allErrors.isEmpty()) {
			return new JsonGenerationResponse(null, allErrors, null);
		}

		try {
			// generate term candidates
			List<TermGenerationInput> generationTasks = createGenerationTasks(ontologyName,
					allParameters);
			List<TermGenerationOutput> candidates = termGeneration.generateTerms(manager.getOntology(), generationTasks);

			// validate candidates
			if (candidates == null || candidates.isEmpty()) {
				return new JsonGenerationResponse(NO_TERMS_GENERATED, null, null);
			}

			List<JsonOntologyTerm> jsonCandidates = new ArrayList<JsonOntologyTerm>();
			List<JsonValidationHint> jsonHints = new ArrayList<JsonValidationHint>();
			for (TermGenerationOutput candidate : candidates) {
				if (candidate.isSuccess()) {
					JsonOntologyTerm jsonCandidate = JsonOntologyTerm.convert(candidate.getTerm(), candidate.getChangedTermRelations());
					jsonCandidates.add(jsonCandidate);
				}
				else {
					JsonTermTemplate template = jsonTools.createJsonTermTemplate(candidate.getInput().getTermTemplate());
					jsonHints.add(new JsonValidationHint(template, -1, candidate.getMessage()));
				}
			}

			JsonGenerationResponse generationResponse = new JsonGenerationResponse(null, jsonHints, jsonCandidates);

			// return response
			return generationResponse;
		} catch (Exception exception) {
			logger.warn("An error occured during the term generation for the parameters: {ontologyName: " + ontologyName + ", allParameters: " + allParameters + "}",
					exception);
			return new JsonGenerationResponse("An internal error occured on the server. Please contact the developers if the problem persists.", null, null);
		}
	}

	private List<TermGenerationInput> createGenerationTasks(String ontologyName,
			List<JsonTermGenerationInput> allParameters)
	{
		List<TermGenerationInput> result = new ArrayList<TermGenerationInput>();
		for (JsonTermGenerationInput jsonInput : allParameters) {
			JsonTermTemplate jsonTemplate = jsonInput.getTermTemplate();
			TermTemplate template = getTermTemplate(ontologyName, jsonTemplate.getName());
			TermGenerationParameters parameters = jsonTools.createTermGenerationParameters(jsonInput.getTermGenerationParameter());
			TermGenerationInput input = new TermGenerationInput(template, parameters);
			result.add(input);
		}
		return result;
	}

	private Collection<TermTemplate> getTermTemplates(String ontology) {
		Collection<TermTemplate> templates;
		synchronized (TEMPLATE_CACHE) {
			templates = TEMPLATE_CACHE.getTemplates(ontology);
			if (templates == null) {
				templates = requestTemplates(ontology);
				TEMPLATE_CACHE.put(ontology, templates);
			}
		}
		return templates;
	}

	private TermTemplate getTermTemplate(String ontology, String name) {
		TermTemplate template;
		synchronized (TEMPLATE_CACHE) {
			template = TEMPLATE_CACHE.getTemplate(ontology, name);
			if (template == null) {
				Collection<TermTemplate> templates = TEMPLATE_CACHE.getTemplates(ontology);
				if (templates == null) {
					templates = requestTemplates(ontology);
					TEMPLATE_CACHE.put(ontology, templates);
				}
				template = TEMPLATE_CACHE.getTemplate(ontology, name);
			}
		}
		return template;
	}

	/**
	 * Request the templates for a given ontology.
	 * 
	 * @param ontology
	 * @return templates, never null
	 */
	protected Collection<TermTemplate> requestTemplates(String ontology) {
		List<TermTemplate> templates = ontologyTools.getTermTemplates(ontology);
		if (templates == null) {
			templates = Collections.emptyList();
		}
		return templates;
	}

	private static final class JsonTermTempleSorter implements Comparator<JsonTermTemplate> {

		private static final JsonTermTempleSorter instance = new JsonTermTempleSorter();
		
		@Override
		public int compare(JsonTermTemplate o1, JsonTermTemplate o2) {
			return o1.getName().compareTo(o2.getName());
		}
	}

	/**
	 * Tools for converting term generation details into the JSON enabled
	 * (transfer) objects.
	 */
	class JsonTemplateTools {

		/**
		 * Convert a single template into a JSON specific data structure.
		 * 
		 * @param template
		 * @return internal format
		 */
		JsonTermTemplate createJsonTermTemplate(TermTemplate template) {
			JsonTermTemplate jsonTermTemplate = new JsonTermTemplate();
			jsonTermTemplate.setName(template.getName());
			jsonTermTemplate.setDisplay(template.getDisplayName());
			jsonTermTemplate.setDescription(template.getDescription());
			jsonTermTemplate.setHint(template.getHint());
			List<TemplateField> fields = template.getFields();
			int size = fields.size();
			List<JsonTemplateField> jsonFields = new ArrayList<JsonTemplateField>(size);
			for (TemplateField field : fields) {
				jsonFields.add(createJsonTemplateField(field));
			}
			jsonTermTemplate.setFields(jsonFields);
			return jsonTermTemplate;
		}

		private JsonTemplateField createJsonTemplateField(TemplateField field) {
			JsonTemplateField jsonField = new JsonTemplateField();
			jsonField.setName(field.getName());
			jsonField.setRequired(field.isRequired());
			Cardinality c = field.getCardinality();
			jsonField.setCardinality(new JsonCardinality(c.getMinimum(), c.getMaximum()));
			jsonField.setFunctionalPrefixes(field.getFunctionalPrefixes().toArray(new String[0]));
			if (field.hasCorrespondingOntologies()) {
				List<Ontology> ontologies = field.getCorrespondingOntologies();
				String[] ontologyNames = new String[ontologies.size()];
				for (int i = 0; i < ontologyNames.length; i++) {
					Ontology ontology = ontologies.get(i);
					ontologyNames[i] = ontologyTools.getOntologyName(ontology);
				}
				jsonField.setOntologies(ontologyNames);
			}
			return jsonField;
		}

		TermGenerationParameters createTermGenerationParameters(JsonTermGenerationParameter json)
		{
			TermGenerationParameters result = new TermGenerationParameters();
			Map<String, List<JsonOntologyTermIdentifier>> terms = json.getTerms();
			for (String field : terms.keySet()) {
				result.setTermValues(field, getTerms(terms.get(field)));
			}
			Map<String, List<String>> strings = json.getStrings();
			if (strings != null && !strings.isEmpty()) {
				for (String field : strings.keySet()) {
					result.setStringValues(field, strings.get(field));
				}
			}
			return result;
		}

		private List<OntologyTerm<ISynonym, IRelation>> getTerms(List<JsonOntologyTermIdentifier> jsonTerms)
		{
			List<OntologyTerm<ISynonym, IRelation>> terms = new ArrayList<OntologyTerm<ISynonym, IRelation>>();
			for (JsonOntologyTermIdentifier jsonTerm : jsonTerms) {
				OntologyTerm<ISynonym, IRelation> term = getOntologyTerm(jsonTerm);
				terms.add(term);
			}
			return terms;
		}

		private OntologyTerm<ISynonym, IRelation> getOntologyTerm(JsonOntologyTermIdentifier jsonOntologyTerm) {
			String ontologyName = jsonOntologyTerm.getOntology();
			OntologyTaskManager manager = ontologyTools.getManager(ontologyName);
			OntologyTermTask task = new OntologyTermTask(jsonOntologyTerm.getTermId());
			manager.runManagedTask(task);
			return task.getTerm();
		}
	}

	private static class OntologyTermTask extends OntologyTask {

		private final String id;
		private OntologyTerm<ISynonym, IRelation> term = null;

		OntologyTermTask(String id) {
			this.id = id;
		}

		
		
		@Override
		protected void runCatching(OWLGraphWrapper realInstance) throws Exception {
			String label = null;
			String definition = null;
			List<ISynonym> synonyms = null;
			List<String> defxref = null;
			Map<String, String> metadata = new HashMap<String, String>();
			List<IRelation> relations = null;

			if (realInstance != null) {
				OWLObject owlObject = realInstance.getOWLObjectByIdentifier(id);
				if (owlObject != null) {
					label = realInstance.getLabel(owlObject);
					if (label != null) {
						definition = realInstance.getDef(owlObject);
						synonyms = realInstance.getOBOSynonyms(owlObject);
						defxref = realInstance.getDefXref(owlObject);
						// meta data
						put(metadata, "comment", realInstance.getComment(owlObject));
						put(metadata, "created_by", realInstance.getCreatedBy(owlObject));
						put(metadata, "resource", realInstance.getNamespace(owlObject));
						// relations
						Set<OWLGraphEdge> outgoingEdges = realInstance.getOutgoingEdges(owlObject);
						if (outgoingEdges != null && !outgoingEdges.isEmpty()) {
							relations = new ArrayList<IRelation>(outgoingEdges.size());
							for (OWLGraphEdge edge : outgoingEdges) {
								String source = realInstance.getIdentifier(edge.getSource());
								OWLObject targetOWLObject = edge.getTarget();
								String target = realInstance.getIdentifier(targetOWLObject);
								String targetLabel = realInstance.getLabel(targetOWLObject);
								Map<String, String> properties = new HashMap<String, String>();
								for (OWLQuantifiedProperty property : edge.getQuantifiedPropertyList()) {
									properties.put(property.getPropertyId(),
											property.getQuantifier().name());
								}
								Relation r = new Relation(source, target, targetLabel, properties);
								relations.add(r);
							}
						}
					}
				}
			}
			term = new DefaultOntologyTerm(id, label, definition, synonyms, defxref, metadata, relations);
		}

		OntologyTerm<ISynonym, IRelation> getTerm() {
			return term;
		}

	}

	private static void put(Map<String, String> map, String key, String value) {
		if (value != null) {
			map.put(key, value);
		}
	}

	static class TemplateCache {

		private static volatile TemplateCache instance = null;
		private final Map<String, Map<String, TermTemplate>> templates;

		private TemplateCache() {
			templates = new HashMap<String, Map<String, TermTemplate>>();
		}

		public synchronized static TemplateCache getInstance() {
			if (instance == null) {
				instance = new TemplateCache();
			}
			return instance;
		}

		void put(String ontology, Collection<TermTemplate> templates) {
			Map<String, TermTemplate> namedValues = new HashMap<String, TermTemplate>();
			for (TermTemplate template : templates) {
				namedValues.put(template.getName(), template);
			}
			if (namedValues.isEmpty()) {
				namedValues = Collections.emptyMap();
			}
			this.templates.put(ontology, namedValues);
		}

		boolean hasOntology(String ontology) {
			return templates.containsKey(ontology);
		}

		Collection<TermTemplate> getTemplates(String ontology) {
			Map<String, TermTemplate> namedValues = templates.get(ontology);
			if (namedValues == null) {
				return null;
			}
			return namedValues.values();
		}

		TermTemplate getTemplate(String ontology, String templateName) {
			Map<String, TermTemplate> namedValues = templates.get(ontology);
			if (namedValues == null) {
				return null;
			}
			return namedValues.get(templateName);
		}
	}
}
